### ISSUE TITLE
Add Other Known Clients

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/toolbox#54]
We should add DLHub and FuncX to KNOWN_CLIENTS before our next rollout. Eventually, we can add Foundry but it's quite ready yet.

**Comment by jgaff** [comment]
The FuncX and DLHub clients (as well as the Forge, SearchHelper, and MDF Connect Clients, which are also not listed in `KNOWN_CLIENTS`) have their own login code and different `__init__` arguments, so they are not eligible for automatic creation with Toolbox. These clients should be initialized by the user, and the clients themselves will handle authentication and token management. The standard Globus SDK clients (Transfer, Search) and the unofficial Groups client (Nexus) do not perform their own auth, and they accept their singular respective authorizers (plus `http_timeout`) as their only important arguments, so it is possible to automatically create these.

If it is confusing to have the list of programmatically-creatable clients named _known_ clients, I can rename it to _globus_ clients or similar. Otherwise, I don't think Toolbox is the right choice for the use case you're addressing - again, all the excluded clients perform their own auth and do not need Toolbox to create an authorizer for them.
